name: flutter_modules
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  desktop_window: ^0.4.0
  flutter_lorem: ^2.0.0

  # Network
  dio: ^5.3.0
  equatable: ^2.0.5
  web_socket_channel: ^2.4.0
  graphql_flutter: ^5.1.2
  pretty_dio_logger: ^1.3.1

  # State Management
  provider: ^6.0.5
  flutter_bloc: ^8.1.3

  # Firebase
  firebase_core: ^2.11.0
  firebase_messaging: ^14.6.9
  firebase_in_app_messaging: ^0.7.3+7

  # Responsive
  responsive_framework: ^1.1.0
  flutter_screenutil: ^5.8.4

  # Cache
  flutter_cache_manager: ^3.3.1

  # Others
  flutter_web_frame: ^1.0.0
  smooth_page_indicator: ^1.1.0
  flutter_local_notifications: ^16.1.0
  go_router: ^11.1.1
  syncfusion_flutter_charts: ^24.2.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_driver:
    sdk: flutter

  # Testing
  test: ^1.24.3
  mocktail: ^1.0.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
